## Install Dependencies

In [1]:
!pip install tensorflow tensorflow-gpu sklearn

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Running setup.py clean for tensorflow-gpu
Failed to build tensorflow-gpu
  Running setup.py install for tensorflow-gpu: started
  Running setup.py install for tensorflow-gpu: finished with status 'error'


  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [18 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\vedga\AppData\Local\Temp\pip-install-73o5i3ul\tensorflow-gpu_ad02b59ea85d4287843fe8fed824878a\setup.py", line 37, in <module>
      raise Exception(TF_REMOVAL_WARNING)
  Exception:
  
  The "tensorflow-gpu" package has been removed!
  
  Please install "tensorflow" instead.
  
  Other than the name, the two packages have been identical
  since TensorFlow 2.1, or roughly since Sep 2019. For more
  information, see: pypi.org/project/tensorflow-gpu
  
  
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tensorflow-gpu
  error: subprocess-exited-with-error
  
  Running setup.py install for tensorflow-gpu did not

## Import Libraries

In [1]:
import os
import pandas as pd
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.11.0'

In [3]:
os.path.join('jigsaw-toxic-comment-classification-challenge', 'train.csv', 'train.csv')

'jigsaw-toxic-comment-classification-challenge\\train.csv\\train.csv'

In [4]:

cwd = os.getcwd()
files = os.listdir(cwd)
print("Files in %r: %s" % (cwd, files))

Files in 'C:\\Users\\vedga\\Desktop\\Projects\\ML-Projects\\Toxic comment Classificaton Model': ['.ipynb_checkpoints', 'jigsaw-toxic-comment-classification-challenge', 'Notes.txt', 'Toxic_Comment_Classification.h5', 'Toxic_Comment_Classification.ipynb']


In [5]:
df = pd.read_csv(os.path.join('jigsaw-toxic-comment-classification-challenge', 'train.csv', 'train.csv'))

In [6]:
df[df['toxic'] == 1].head()

id                                       comment_text  \
6   0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK   
12  0005c987bdfc9d4b  Hey... what is it..\n@ | talk .\nWhat is it......   
16  0007e25b2121310b  Bye! \n\nDon't look, come or think of comming ...   
42  001810bf8c45bf5f  You are gay or antisemmitian? \n\nArchangel WH...   
43  00190820581d90ce           FUCK YOUR FILTHY MOTHER IN THE ASS, DRY!   

    toxic  severe_toxic  obscene  threat  insult  identity_hate  
6       1             1        1       0       1              0  
12      1             0        0       0       0              0  
16      1             0        0       0       0              0  
42      1             0        1       0       1              1  
43      1             0        1       0       1              0

In [7]:
df.tail()

id                                       comment_text  \
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0

In [8]:
df.iloc[4]['comment_text']

"You, sir, are my hero. Any chance you remember what page that's on?"

In [9]:
df[df.columns[2:]].iloc[5]

toxic            0
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
Name: 5, dtype: int64

## Preprocess

In [10]:
!pip list

Package                            Version
---------------------------------- --------------------
absl-py                            1.4.0
aiofiles                           23.1.0
aiohttp                            3.8.4
aiosignal                          1.3.1
alabaster                          0.7.12
altair                             4.2.2
anaconda-client                    1.9.0
anaconda-navigator                 2.1.1
anaconda-project                   0.10.1
anyio                              3.6.2
appdirs                            1.4.4
argh                               0.26.2
argon2-cffi                        20.1.0
arrow                              0.13.1
asn1crypto                         1.4.0
astroid                            2.6.6
astropy                            4.3.1
astunparse                         1.6.3
async-generator                    1.10
async-timeout                      4.0.2
atomicwrites                       1.4.0
attrs                              

In [11]:
from tensorflow.keras.layers import TextVectorization

In [12]:
df.columns[2:]

Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')

In [13]:
df[df.columns[2:]]

toxic  severe_toxic  obscene  threat  insult  identity_hate
0           0             0        0       0       0              0
1           0             0        0       0       0              0
2           0             0        0       0       0              0
3           0             0        0       0       0              0
4           0             0        0       0       0              0
...       ...           ...      ...     ...     ...            ...
159566      0             0        0       0       0              0
159567      0             0        0       0       0              0
159568      0             0        0       0       0              0
159569      0             0        0       0       0              0
159570      0             0        0       0       0              0

[159571 rows x 6 columns]

In [14]:
df[df.columns[2:]].values #can pass this through the NN as each comment is a vector

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [15]:
X = df['comment_text']
y = df[df.columns[2:]].values

In [16]:
X

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: object

In [17]:
y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [18]:
MAX_FEATURES = 200000 # number of word in the vocabulray

In [19]:
## output_sequence_length --> Max length of our sentence, sentence length in token
## Each sentence from our input,  length will be capped to 1800 words
## output_mode --> Map every single word to an integer

In [20]:
vectorizer = TextVectorization(max_tokens = MAX_FEATURES, output_sequence_length= 1800, output_mode='int')

### Note: -
The vocabulary for the layer must be either supplied on construction or learned via adapt(). When this layer is adapted, it will analyze the dataset, determine the frequency of individual string values, and create a vocabulary from them. This vocabulary can have unlimited size or be capped, depending on the configuration options for this layer; if there are more unique values in the input than the maximum vocabulary size, the most frequent terms will be used to create the vocabulary.

In [21]:
type(X)

pandas.core.series.Series

In [22]:
type(X.values)

numpy.ndarray

In [23]:
vectorizer.adapt(X.values)

In [24]:
vectorizer('Hello there, life is happy')

<tf.Tensor: shape=(1800,), dtype=int64, numpy=array([288,  41, 306, ...,   0,   0,   0], dtype=int64)>

In [25]:
vectorizer.get_vocabulary() # return array of each of thw words, and the position in the array represents the what number from the sequence is the particular word

['',
 '[UNK]',
 'the',
 'to',
 'of',
 'and',
 'a',
 'you',
 'i',
 'is',
 'that',
 'in',
 'it',
 'for',
 'this',
 'not',
 'on',
 'be',
 'as',
 'have',
 'are',
 'your',
 'with',
 'if',
 'article',
 'was',
 'or',
 'but',
 'page',
 'my',
 'an',
 'from',
 'by',
 'do',
 'at',
 'about',
 'me',
 'so',
 'wikipedia',
 'can',
 'what',
 'there',
 'all',
 'has',
 'will',
 'talk',
 'please',
 'would',
 'its',
 'no',
 'one',
 'just',
 'like',
 'they',
 'he',
 'dont',
 'which',
 'any',
 'been',
 'should',
 'more',
 'we',
 'some',
 'other',
 'who',
 'see',
 'here',
 'also',
 'his',
 'think',
 'im',
 'because',
 'know',
 'how',
 'am',
 'people',
 'why',
 'edit',
 'articles',
 'only',
 'out',
 'up',
 'when',
 'were',
 'use',
 'then',
 'may',
 'time',
 'did',
 'them',
 'now',
 'being',
 'their',
 'than',
 'thanks',
 'even',
 'get',
 'make',
 'good',
 'had',
 'very',
 'information',
 'does',
 'could',
 'well',
 'want',
 'such',
 'sources',
 'way',
 'name',
 'these',
 'deletion',
 'pages',
 'first',
 'help'

In [26]:
vectorized_text = vectorizer(X.values)

In [27]:
len(X)

159571

In [28]:
vectorized_text

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]], dtype=int64)>

In [31]:
#Tensorflow datapipeline
# MCSBAP - MAP, CHACHE, SHUFFLE, BATCH, PREFETCH from tensor_slices, list_files
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text, y))
dataset = dataset.cache()
dataset = dataset.shuffle(160000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8) # helps prevet bottlenecks

In [32]:
batch_X, batch_y = dataset.as_numpy_iterator().next()

In [33]:
batch_X # Vectorized text examples

array([[  124,     7,    13, ...,     0,     0,     0],
       [    5,     2,   701, ...,     0,     0,     0],
       [   21,  3953, 19519, ...,     0,     0,     0],
       ...,
       [    8,   151,    12, ...,     0,     0,     0],
       [  433,   176,   637, ...,     0,     0,     0],
       [16039,    13,    62, ...,     0,     0,     0]], dtype=int64)

In [34]:
batch_X.shape

(16, 1800)

In [35]:
batch_y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [36]:
batch_y.shape

(16, 6)

In [37]:
len(dataset) #batch,  we multiply by 16 we get the no of sample

9974

In [38]:
train = dataset.take(int(len(dataset)*0.7)) # take 70% of dataset for training
val = dataset.skip(int(len(dataset)*0.7)).take(int(len(dataset)*0.2)) # skip the 70% datset and then take 20% from other part for validation set
test = dataset.skip(int(len(dataset)*0.9)).take(int(len(dataset)*0.1)) # skip 90% and take the remaining 10% for training test

In [39]:
len(train)

6981

In [40]:
len(val)

1994

In [41]:
len(test)

997

In [42]:
train_generator = train.as_numpy_iterator()

In [43]:
train_generator.next() # to get the next batch, changes every time

(array([[  191,   288,     5, ...,     0,     0,     0],
        [ 1211,    14,    24, ...,     0,     0,     0],
        [   94,    13,    21, ...,     0,     0,     0],
        ...,
        [    2, 12509,   408, ...,     0,     0,     0],
        [   70,   130, 12523, ...,     0,     0,     0],
        [    8,    47,   185, ...,     0,     0,     0]], dtype=int64),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]], dtype=int64))

## Create the Sequential Model

In [44]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Bidirectional, Dense, Embedding

In [45]:
model = Sequential()
# create the embedding layer
model.add(Embedding(MAX_FEATURES + 1, 32)) # no of words +1(for unknown words), 32 length of each embedding
# Create Bidirectional LSTM layer
model.add(Bidirectional(LSTM(32, activation = 'tanh'))) # Bidirectional LSTM is needed particulary for sentences(may need previous modifier words)
# Feature extractor Fully Connected Layer
model.add(Dense(128, activation = 'relu'))
model.add(Dense(256, activation = 'relu'))
model.add(Dense(128, activation = 'relu'))
#Final layer --> We have 6 different outputs
model.add(Dense(6, activation = 'sigmoid'))

In [46]:
y[0]

array([0, 0, 0, 0, 0, 0], dtype=int64)

In [47]:
model.compile(loss = 'BinaryCrossentropy', optimizer = 'Adam')
# No categorical crossentropy ? 6outputs --> no ,its not like we will get 1 value from the 6 classes
# It is like we are running 6 different binary classifiers at one time

In [48]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          6400032   
                                                                 
 bidirectional (Bidirectiona  (None, 64)               16640     
 l)                                                              
                                                                 
 dense (Dense)               (None, 128)               8320      
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 6)                 774       
                                                        

In [48]:
history = model.fit(train, epochs = 1, validation_data = val)

6981/6981 [==============================] - 7529s 1s/step - loss: 0.0625 - val_loss: 0.0458


In [49]:
from matplotlib import pyplot as plt

### Here we are not getting graph because only run for 1 epoch

In [50]:
plt.figure(figsize=(8,5))
pd.DataFrame(history.history).plot()
plt.show()

NameError: name 'history' is not defined

<Figure size 576x360 with 0 Axes>

## Make Predictions

In [51]:
input_text = vectorizer('You freaking suck! I am going to hit you.')

In [52]:
res = model.predict(np.expand_dims(input_text, 0))

1/1 [==============================] - 1s 1s/step


In [53]:
(res > 0.5).astype(int)

array([[1, 0, 0, 0, 1, 0]])

In [54]:
batch_X, batch_y = test.as_numpy_iterator().next()

In [55]:
(model.predict(batch_X) > 0.5)

1/1 [==============================] - 0s 224ms/step


array([[ True, False, False, False, False, False],
       [ True, False, False, False,  True, False],
       [ True, False, False, False,  True, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False,  True, False],
       [False, False, False, False,  True, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False,  True, False],
       [ True, False, False, False,  True, False],
       [ True, False, False, False, False, False],
       [False, False, False, False,  True, False],
       [ True, False, False, False,  True, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False,  True, False]])

In [56]:
(model.predict(batch_X) > 0.5).astype(int)

1/1 [==============================] - 0s 135ms/step


array([[1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0]])

In [57]:
res.shape

(1, 6)

## Evaluate Model

In [58]:
from tensorflow.keras.metrics import Precision, Recall, CategoricalAccuracy

In [59]:
pre = Precision()
re = Recall()
acc = CategoricalAccuracy()

In [61]:
for batch in test.as_numpy_iterator(): 
    # Unpack the batch 
    X_true, y_true = batch
    # Make a prediction 
    yhat = model.predict(X_true)
    
    # Flatten the predictions
    y_true = y_true.flatten()
    yhat = yhat.flatten()
    
    pre.update_state(y_true, yhat)
    re.update_state(y_true, yhat)
    acc.update_state(y_true, yhat)

1/1 [==============================] - 0s 134ms/step


1/1 [==============================] - 0s 132ms/step


1/1 [==============================] - 0s 134ms/step


1/1 [==============================] - 0s 170ms/step


1/1 [==============================] - 0s 139ms/step


1/1 [==============================] - 0s 107ms/step


1/1 [==============================] - 0s 123ms/step


In [62]:
print(f'Precision: {pre.result().numpy()}, Recall:{re.result().numpy()}, Accuracy:{acc.result().numpy()}')

Precision: 0.8297947645187378, Recall:0.6563112139701843, Accuracy:0.44734203815460205


## Test and Gradio App

In [64]:
!pip install gradio jinja2

     ---------------------------------------- 15.8/15.8 MB 1.4 MB/s eta 0:00:00
     -------------------------------------- 202.8/202.8 kB 1.4 MB/s eta 0:00:00
  Using cached aiofiles-23.1.0-py3-none-any.whl (14 kB)
     -------------------------------------- 813.6/813.6 kB 1.8 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached websockets-10.4-cp39-cp39-win_amd64.whl (101 kB)
     ---------------------------------------- 45.7/45.7 kB 2.2 MB/s eta 0:00:00
     ---------------------------------------- 56.4/56.4 kB ? eta 0:00:00
     ---------------------------------------- 71.5/71.5 kB 1.3 MB/s eta 0:00:00
  Using cached aiohttp-3.8.4-cp39-cp39-win_amd64.whl (323 kB)
     ---------------------------------------- 84.5/84.5 kB 2.3 MB/s eta 0:00:00
     ---------------------------------------- 2.2/2.2 MB 1.6 MB/s eta 0:00:00
     ---------------------------------------- 50.5/50.5 kB 1.3 MB/s eta 0:00:00
     

In [60]:
import gradio as gr

In [61]:
model.save('Toxic_Comment_Classification.h5')

In [62]:
model = tf.keras.models.load_model('Toxic_Comment_Classification.h5')

In [63]:
input_str = vectorizer('hey i freaken hate you!')

In [64]:
res = model.predict(np.expand_dims(input_str,0))

1/1 [==============================] - 1s 783ms/step


In [66]:
def score_comment(comment):
    vectorized_comment = vectorizer([comment])
    results = model.predict(vectorized_comment)
    
    text = ''
    for idx, col in enumerate(df.columns[2:]):
        text += '{}: {}\n'.format(col, results[0][idx]>0.5)
    
    return text

In [67]:
interface = gr.Interface(fn=score_comment, 
                         inputs=gr.inputs.Textbox(lines=2, placeholder='Comment to score'),
                        outputs='text')

C:\Users\vedga\anaconda3\lib\site-packages\gradio\inputs.py:27: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
C:\Users\vedga\anaconda3\lib\site-packages\gradio\deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect
  warnings.warn(value)
C:\Users\vedga\anaconda3\lib\site-packages\gradio\deprecation.py:40: UserWarning: `numeric` parameter is deprecated, and it has no effect
  warnings.warn(value)


In [68]:
interface.launch(share=True)

Running on local URL:  http://127.0.0.1:7860

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app


1/1 [==============================] - 0s 100ms/step
